### ISSUE TITLE
s2Clean Markdown Filters (Explained)

### ISSUE THREAD

**Issue by raamdev** [wpsharks/s2clean-kb#1]
---
##### KB Article Creation Checklist
- [x] Write initial draft for this KB Article; label this issue `draft` and either `questions` or `tutorials`
- [x] Add [required YAML configuration](https://github.com/websharks/team/wiki/KB-Articles-::-Required-YAML-Configuration)
- [ ] Add Tags for this KB Article to the YAML config (see [YAML Keys (Explained)](https://github.com/websharks/team/wiki/KB-Articles-::-Required-YAML-Configuration#yaml-keys-explained))
- [ ] Edit and finalize draft for publishing (remove `draft` label, add `draft-finalized` label)
- [ ] Assign Issue to yourself and [create Markdown file](https://github.com/websharks/team/wiki/KB-Articles-::-Creating-the-Markdown-File) (remove `draft-finalized` label, add `pending`)
- [ ] Project Lead: Review and Publish KB Article (remove `pending` label, add `published` label)
##### Additional TODOs

_Additional TODO list items go here._

``` yaml
title: s2Clean Markdown Filters (Explained)
categories: tutorials
tags: 
author: raamdev
github-issue: https://github.com/websharks/s2clean-kb/issues/1
```

---

![md-the_content](https://cloud.githubusercontent.com/assets/1563559/6202614/e045c4ec-b4a1-11e4-8c84-6f087ebd183a.png)

Also referencing: https://github.com/websharks/s2clean/issues/21#issuecomment-74408878
